# Generated by Django 4.2.11 on 2024-04-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_service_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['popular']},
        ),
    ]
